### PR TITLE
- More SI based unit conversions.

### PR DESCRIPTION
**Pull request by Xliff**
Here are more of the units from the old project's definitions file. I will work on finishing those up plus adding more as time allows.

A few questions:
- When is it appropriate to use $.plural-name. Some units set it, others don't.
- What is the best way to use a unit comprised of more than one derived units?

Thanks!

### CODE REVIEW

**Comment by holli-holzer** [comment]
Hi.

Thanks a lot for this. It's "Siemens" though, not "Siemen".


"When is it appropriate to use $.plural-name. Some units set it, others
don't"

When the plural differs from the singular, like in 1 foot, 2 feet. Unlike 1
ampere, 2 ampere.

"What is the best way to use a unit comprised of more than one derived
units?"

Example?

**Comment by Xliff** [comment]
I don't have a ready example for the DerivedUnits question, just a thought from my attempt at a similar module. If it comes up again, we can circle back.

**Comment by holli-holzer** [comment]
Well in general, everything (known) physical can be expressed in SI units
somehow, can't it?

But if you wanted a unit Gobbledigook (G) with 1G equaling 7 Dadamuchis
(Dm), you can do that.
You would just have to define the class Gobbledigook as SIUnit instead of
DerivedUnit.

**Comment by Xliff** [comment]
HAH! I thought that was how it was going to go. OK. I have completed the definitions with this latest commit.

**Comment by Xliff** [comment]
OK. New procedure. Only add plural names to units that need one.

**Comment by Xliff** [comment]
One other thing... the Line unit doesn't seem to have a consistent specification, there being a British _and_ a Paris version. Will need to narrow that down.

Will add Yard, shortly.

**Comment by Xliff** [comment]
Looking over the code, there may be a problem dealing with Teslas in the tera range, bexause they have the same symbol. Aside from changing one symbol or the other, I don't have any good solutions. Thoughts?

**Comment by holli-holzer** [comment]
I know. The same problem appears with "milli" and "metre". I'm not sure yet. One can either make https://github.com/holli-holzer/perl6-Units-Prefixes a bit smarter or define extra TT and mm operators.

**Comment by Xliff** [comment]
And this brings my bit to a pause.  I think its time we take stock abd see where we are and start planning on where we want to go.

I can keep on adding units, if you want tho!

**Comment by Xliff** [comment]
Also, it might be nice to have a symbol collision test that performs at run-time. This would throw a warning if there are two modules that use the same symbol and communicate that to the user.

**Comment by Xliff** [comment]
Has the Singleton class been implemented, yet... or am I missing a module?

**Comment by holli-holzer** [comment]
https://github.com/holli-holzer/perl6-Singleton

**Comment by Xliff** [comment]
Holli, what about degree and radians (and steradians for that matter), They are dimensionless numbers since they are only numeric measurements, but other units (like the Lumen) depend on their definition.

**Comment by holli-holzer** [comment]
Most definitly.

**Comment by Xliff** [comment]
So how would those be implemented? Would we add additional signatures for them in .si-signature?

**Comment by holli-holzer** [comment]
"They are dimensionless numbers"

**Comment by Xliff** [comment]
That is according to Wikipedia, yet they do have a "signature":
  - radians (rad)
  - steradians (sd)

 A Lumen is cd * sr (also from Wikipedia), so which explanation is correct?

Thanks.

**Pull request merged**
